/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    Admin: typeof import('./src/components/Templates/Admin/Admin.vue')['default']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    AtomButton: typeof import('./src/components/Atoms/AtomButton/AtomButton.vue')['default']
    AtomLoaderSpiner: typeof import('./src/components/Atoms/AtomLoaderSpiner/AtomLoaderSpiner.vue')['default']
    Auth: typeof import('./src/components/Templates/Auth/Auth.vue')['default']
    Dashboard: typeof import('./src/components/Pages/Admin/Dashboard/Dashboard.vue')['default']
    Detail: typeof import('./src/components/Pages/Admin/User/components/Detail/Detail.vue')['default']
    LinkItem: typeof import('./src/components/Molecules/MoleculeNavbar/MenuDropdown/LinkItem/LinkItem.vue')['default']
    List: typeof import('./src/components/Pages/Admin/User/components/List/List.vue')['default']
    Login: typeof import('./src/components/Pages/Auth/Login/Login.vue')['default']
    MoleculeBreadcrumbs: typeof import('./src/components/Molecules/MoleculeBreadcrumbs/MoleculeBreadcrumbs.vue')['default']
    MoleculeTitlePageActionTop: typeof import('./src/components/Molecules/MoleculeTitlePageActionTop/MoleculeTitlePageActionTop.vue')['default']
    OrganismsNavbar: typeof import('./src/components/Organisms/OrganismsNavbar/OrganismsNavbar.vue')['default']
    OrganismsSidebar: typeof import('./src/components/Organisms/OrganismsSidebar/OrganismsSidebar.vue')['default']
    OrganismsUserForm: typeof import('./src/components/Organisms/OrganismsUserForm/OrganismsUserForm.vue')['default']
    PageNotFound: typeof import('./src/components/Templates/PageNotFound/PageNotFound.vue')['default']
    Profile: typeof import('./src/components/Pages/Admin/Profile/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/Pages/Admin/User/User.vue')['default']
  }
}
